spring:
  application:
    ## 多个应用相同的name则为客户端侧的负载均衡
    name: eureka-client1
server:
  port: 22002
eureka:
  client:
    service-url:
      ## 属性对应服务注册中心的配置内容，指定服务注册中心的位置，该属性yml不会自动联想，注意务必带/eureka/
      defaultZone: http://192.168.8.36:22001/eureka/

##  访问地址: http://192.168.8.36:22002/dc