spring:
  application:
    name: eureka-consumer-feign
server:
  port: 22009
eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.36:22001/eureka/

## ∑√Œ µÿ÷∑: http://192.168.8.36:22009/consumer