spring:
  application:
    name: eureka-consumer-ribbon-hystrix
server:
  port: 22010
eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.36:22001/eureka/

## ∑√Œ µÿ÷∑: http://192.168.8.36:22010/consumer