spring:
  application:
    name: eureka-server
server:
  port: 22001
eureka:
  instance:
    hostname: localhost
  ## 在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
  client:
    register-with-eureka: false
    fetch-registry: false

## 访问地址: http://192.168.8.36:22001/
## eureka服务端